name: Pull Request Labeler

on:
  pull_request_target:
    types:
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Labeling pull requests
        uses: actions/labeler@v4
