name: Create release

on:
  push:
    tags:
      - "**"

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: tag_name
        run: |
          PUSHED_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          IFS="/" read -ra TAG_PARTS <<< "$PUSHED_TAG"
          PACKAGE_NAME="${TAG_PARTS[0]}"
          echo "package_name=$PACKAGE_NAME" >> "$GITHUB_OUTPUT"

      - name: Parse Changelog
        id: changelog
        uses: ocavue/changelog-parser-action@v1
        with:
          removeMarkdown: false
          filePath: "./packages/${{ steps.tag_name.outputs.package_name }}/CHANGELOG.md"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.latestBody }}
          draft: false
          prerelease: false
