name: Create release

on:
  push:
    tags:
    - '**'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF_NAME}
        shell: bash

      - name: Get package and version name
        uses: jungwinter/split@v2
        id: split
        with: 
          msg: ${{steps.tag_name.outputs.current_version}}
          separator: '/'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get changelog entries
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.split.outputs._0 }} ${{ steps.split.outputs._1 }}
          path: ./packages/${{ steps.split.outputs._0 }}/CHANGELOG.md

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          tag: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
