name: Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.0'

      - name: Setup module dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install module dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.js
