name: Test Suite

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20.19.4
          cache: 'npm'

      - name: Install module dependencies
        run: |
          npm ci
          # Ensure Biome binary for Linux is installed
          npm install @biomejs/cli-linux-x64 --no-save --force

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm test

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.cjs
